USE DATABASE SANDBOX_DB;
USE SCHEMA ICEBERG_DEMO;
USE WAREHOUSE DE_WH;

CREATE EXTERNAL VOLUME MY_ICEBERG_VOLUME
  STORAGE_LOCATIONS = (
    (
      NAME='primary',
      STORAGE_PROVIDER='S3',
      STORAGE_BASE_URL='s3://<s3 bucket name>/iceberg/',
      STORAGE_AWS_ROLE_ARN='arn:aws:iam::<arn>:role/<rolename>'
    )
  )
  ALLOW_WRITES=TRUE;


ALTER SCHEMA SANDBOX_DB.ICEBERG_DEMO
SET EXTERNAL_VOLUME = 'MY_ICEBERG_VOLUME';

DESC EXTERNAL VOLUME MY_ICEBERG_VOLUME;