CREATE OR REPLACE TABLE SANDBOX_DB.ICEBERG_DEMO.ORDERS_RAW AS
SELECT 
    SEQ4() AS ORDER_ID,
    CONCAT('customer', UNIFORM(1,5000,RANDOM()), '@gmail.com') AS CUSTOMER_EMAIL,
    CONCAT('Customer_', UNIFORM(1,5000,RANDOM())) AS CUSTOMER_NAME,
    ROUND(UNIFORM(10, 500, RANDOM()), 2) AS ORDER_TOTAL,
    DATEADD(DAY, UNIFORM(-365,0,RANDOM()), CURRENT_TIMESTAMP()) AS CREATED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

SELECT * FROM SANDBOX_DB.ICEBERG_DEMO.ORDERS_RAW LIMIT 10;
