CREATE OR REPLACE ICEBERG TABLE SANDBOX_DB.ICEBERG_DEMO.ORDERS_ICEBERG
CATALOG = 'SNOWFLAKE'
AS
SELECT
    ORDER_ID,
    CUSTOMER_EMAIL,
    CUSTOMER_NAME,
    ORDER_TOTAL,
    CAST(CREATED_AT AS TIMESTAMP_NTZ(6)) AS CREATED_AT
FROM SANDBOX_DB.ICEBERG_DEMO.ORDERS_RAW;

SELECT * FROM SANDBOX_DB.ICEBERG_DEMO.ORDERS_ICEBERG LIMIT 10;
