CREATE OR REPLACE TABLE SANDBOX_DB.ICEBERG_DEMO.CATALOG_DOCS AS
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    TABLE_NAME,
    SNOWFLAKE.CORTEX.COMPLETE(
        'mistral-large',
        'In clear business terms, explain what the column "' || COLUMN_NAME ||
        '" in table SANDBOX_DB.ICEBERG_DEMO.ORDERS_ICEBERG represents.'
    ) AS DESCRIPTION
FROM SANDBOX_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ICEBERG_DEMO'
  AND TABLE_NAME  = 'ORDERS_ICEBERG';

SELECT * FROM SANDBOX_DB.ICEBERG_DEMO.CATALOG_DOCS;
