CREATE OR REPLACE VIEW SANDBOX_DB.ICEBERG_DEMO.ORDERS_ICEBERG_DOC AS
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    SNOWFLAKE.CORTEX.COMPLETE(
        'mistral-large',
        'Explain the purpose and business meaning of column "' || COLUMN_NAME ||
        '" in table SANDBOX_DB.ICEBERG_DEMO.ORDERS_ICEBERG.'
    ) AS DESCRIPTION
FROM SANDBOX_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ICEBERG_DEMO'
  AND TABLE_NAME  = 'ORDERS_ICEBERG';

SELECT * FROM SANDBOX_DB.ICEBERG_DEMO.ORDERS_ICEBERG_DOC;
